# Advent of code

In [1]:
#using Pkg
#Pkg.add("DataFrames")
using DataFrames

In [2]:
function read_array(day; ncol::Int=1, sep=isspace)
    i = split(strip(read(joinpath(@__DIR__, "./input/day$day.txt"), String)), sep)
    i = reshape(i, ncol, :)
    return permutedims(i)
end

read_array (generic function with 1 method)

## Day 1

In [3]:
function sum_of_two(a, sum)
    for i in 1:length(a)
        for j in i+1:length(a)
            if a[i] + a[j] == sum
                return a[i] , a[j]
            end
        end
    end
end

sum_of_two (generic function with 1 method)

In [4]:
a, b = sum_of_two(parse.(Int,read_array(1)), 2020)

(1314, 706)

In [5]:
a*b

927684

In [6]:
function sum_of_three(a, sum)
    for i in 1:length(a)
        for j in i+1:length(a)
            for k in j+1:length(a)
                if a[i] + a[j] + a[k]  == 2020
                    return a[i] , a[j], a[k]
                end
            end
        end
    end
end

sum_of_three (generic function with 1 method)

In [7]:
a,b,c = sum_of_three(parse.(Int,read_array(1)), 2020)

(811, 532, 677)

In [8]:
a*b*c

292093004

## Day 2

In [9]:
function valid_password(a)
   valid = 0
    # replace all ":"
    a[:,2] = replace.(a[:,2], ":"=>"")
    
  
    
    for i in 1:size(a)[1]
        row = a[i,:]
        pattern = "[" * row[2] * "]"
        pattern = Regex(pattern)
        count = length(collect(eachmatch(pattern, row[3])))
        min, max = parse.(Int,split(row[1], "-"))
        if count >= min && count <= max
            valid = valid + 1
        end
    end
    return valid
end

valid_password (generic function with 1 method)

In [10]:
valid_password(read_array(2, ncol=3))

393

In [11]:
function valid_password_2(a)
   valid = 0
    # replace all ":"
    a[:,2] = replace.(a[:,2], ":"=>"")
    
    for i in 1:size(a)[1]
        row = a[i,:]
        # get positions
        p1, p2 = parse.(Int,split(row[1], "-"))
        
        # compar chars (therefore subset with [1] or [p1])
        if (row[3][p1] == row[2][1]) ⊻ (row[3][p2] == row[2][1])
            valid = valid + 1
        end
    end
    return valid
end

valid_password_2 (generic function with 1 method)

In [12]:
valid_password_2(read_array(2, ncol=3))

690

## Day 3

In [13]:
function forest_walk(a; inc_x=3, inc_y=1)
   x,y = 1,1
    count_trees = 0
    # until the end
    while y <= size(a)[1]
        if a[y,x] == "#"
            count_trees = count_trees+1
        end
        # if x > ncol, start from 1
        x = mod1(x+inc_x, size(a)[2])
        y = y+inc_y
    end
    return count_trees
end

forest_walk (generic function with 1 method)

In [14]:
forest_walk(read_array(3, sep=r"\n|", ncol=31))

294

In [15]:
slopes = [[1,1],
          [3,1],
          [5,1],
          [7,1],
          [1,2]
          ]

5-element Array{Array{Int64,1},1}:
 [1, 1]
 [3, 1]
 [5, 1]
 [7, 1]
 [1, 2]

In [16]:
trees = []
for slope in slopes
    append!(trees, forest_walk(read_array(3, sep=r"\n|", ncol=31), inc_x=slope[1], inc_y=slope[2]))
end
trees

5-element Array{Any,1}:
  75
 294
  79
  85
  39

In [17]:
prod(trees)

5774564250

## Day 4

In [18]:
function validate_passports(list)
    list = split.(list)
    valid_passports = 0
    for passport in list
        passport = split.(passport, ":")
        d = Dict(i[1] => i[2] for i in passport)
        if all(in(keys(d)).(["byr", "iyr", "eyr", "hgt", "hcl", "ecl", "pid"]))
            #display("valid")
            valid_passports = valid_passports+1

        end
        #display(passport)
    end
    return valid_passports
end


validate_passports (generic function with 1 method)

In [19]:
d = validate_passports(read_array(4, sep=r"\n\n"))

254

In [20]:
function validate_entries(passport)
   # byr (Birth Year) - four digits; at least 1920 and at most 2002.
    byr_valid = false
    byr = passport["byr"]
    if occursin(r"^[0-9]{4}$", byr) && parse(Int, byr) >= 1920 && parse(Int, byr) <= 2002
        byr_valid = true
        #display("byr true")
    end
    
    # iyr (Issue Year) - four digits; at least 2010 and at most 2020.
    iyr_valid = false
    iyr = passport["iyr"]
     if occursin(r"^[0-9]{4}$", iyr) && parse(Int, iyr) >= 2010 && parse(Int, iyr) <= 2020
        iyr_valid = true
        #display("iyr true")
    end
    
    #eyr (Expiration Year) - four digits; at least 2020 and at most 2030.
    eyr_valid = false
    eyr = passport["eyr"]
     if occursin(r"^[0-9]{4}$", eyr) && parse(Int, eyr) >= 2020 && parse(Int, eyr) <= 2030
        eyr_valid = true
        #display("eyr true")
    end
    
    #hgt (Height) - a number followed by either cm or in:
    #    If cm, the number must be at least 150 and at most 193.
    #    If in, the number must be at least 59 and at most 76.
    hgt_valid = false
    hgt = passport["hgt"]
    if occursin(r"^[0-9]{2,3}(cm|in)$", hgt)
        n = match(r"^[0-9]{2,3}", hgt)
        n = parse(Int, n.match)
        if occursin(r"in$", hgt) && n >= 59 && n <= 76
            hgt_valid = true
            #display("hgt true")
        elseif occursin(r"cm$", hgt) && n >= 150 && n <= 193
            hgt_valid = true  
            #display("hgt true")
        end
    end

    #hcl (Hair Color) - a # followed by exactly six characters 0-9 or a-f.
    hcl_valid = false
    hcl = passport["hcl"]
    if occursin(r"^#[0-9a-f]{6}$", hcl)
        hcl_valid = true
        #display("hcl true")
    end
    
    #ecl (Eye Color) - exactly one of: amb blu brn gry grn hzl oth.
    ecl_valid = false
    ecl = passport["ecl"]
    if occursin(r"^(amb|blu|brn|gry|grn|hzl|oth)$", ecl)
        ecl_valid = true
        #display("ecl true")
    end

    pid_valid = false
    pid = passport["pid"]
    if occursin(r"^[0-9]{9}$", pid)
        pid_valid = true
        #display("pid true")
    end

    return byr_valid & iyr_valid & eyr_valid & hgt_valid & hcl_valid & ecl_valid & pid_valid
    
end

validate_entries (generic function with 1 method)

In [21]:
function validate_passports_2(list)
    list = split.(list)
    valid_passports = 0
    for passport in list
       passport = split.(passport, ":")
        d = Dict(i[1] => i[2] for i in passport)
        if all(in(keys(d)).(["byr", "iyr", "eyr", "hgt", "hcl", "ecl", "pid"]))
            if validate_entries(d)
               valid_passports = valid_passports+1 
            end

        end
    end
    return valid_passports
end

validate_passports_2 (generic function with 1 method)

In [22]:
validate_passports_2(read_array(4, sep=r"\n\n"))

184

## Day 5

In [23]:
function parse_seats(seats)
    res = DataFrame(row = Int64[], seat = Int64[], id = Int64[])
   for s in seats
        row_code = match(r"^[BF]*", s)
        row_code = row_code.match
        
        row_number = parse_letter_code(row_code, collect(1:2^length(row_code)))
        
        seat_code = match(r"[RL]*$", s)
        seat_code = seat_code.match
        seat_number = parse_letter_code(seat_code, collect(1:2^length(seat_code)), low="L", high="R")
        push!(res, [row_number, seat_number, row_number*8 + seat_number])
    end
    return res
end

parse_seats (generic function with 1 method)

In [24]:
function parse_letter_code(letter_code, r; low="F", high="B")
    half = fld(length(r), 2)
    if letter_code[1] == low[1]
        r = r[1:half]
    elseif letter_code[1] == high[1]
        r = r[half+1:end]
    end
    if length(r) == 1
        # -1 (rows start 1 0)
        return r[1] - 1
    else
        return parse_letter_code(letter_code[2:end], r, low=low, high=high)
    end
end

parse_letter_code (generic function with 1 method)

In [25]:
parse_seats(["BFFFBBFRRR", "FFFBBBFRRR", "BBFFBBFRLL"])

3×3 DataFrame
 Row │ row    seat   id    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │    70      7    567
   2 │    14      7    119
   3 │   102      4    820

In [26]:
maximum(parse_seats(read_array(5))[:,:id])

989

In [27]:
# part B

In [28]:
ids = sort(parse_seats(read_array(5))[:,:id]);

In [29]:
for i in 2:length(ids)-1
    if ids[i] + 2 == ids[i+1]
        display(ids[i] + 1)
    end
end

548

## Day 6 

In [30]:
function unique_answers(groups)
   groups = replace.(groups, "\n"=>"")
    return [length(unique(i)) for i in groups]
end

unique_answers (generic function with 1 method)

In [31]:
sum(unique_answers(read_array(6, sep=r"\n\n")))

6726

In [32]:
function unique_answers_all(groups)
   groups_merged = replace.(groups, "\n"=>"")
    u = [unique(i) for i in groups]
    res = []
    for i in 1:length(groups)
        a = 0  
       for  letter in u[i]
            if all(occursin.(letter, split(groups[i])))
                a = a+1
            end
        end    
        append!(res, a)
    end
    return(res)
end

unique_answers_all (generic function with 1 method)

In [33]:
sum(unique_answers_all(read_array(6, sep=r"\n\n")))

3316

## Day 7

In [34]:
function generate_tree(rules)
    d = Dict()
    for r in rules
        r = replace(r, "bags" => "bag")
        parent, children = split(r, " contain ")
        children = replace.(children, "."=>"")
        children = replace.(children, "no other bag"=>"")
        children = split.(children, ", ")
        c = Dict()
        for child in children
            if child != ""
                bag = strip(match(r"[a-z ]*$", child).match)
                no = parse(Int, match(r"[0-9]*", child).match)
                c[bag] = no
            end
        end
        d[parent] = c
    end
    return d
    
end

generate_tree (generic function with 1 method)

In [35]:
function is_child(tree, parent, bag)
    children = tree[parent]
    if length(children) == 0
        return false
    end
    if bag in keys(children)
        return true
    end
    return any([is_child(tree, child, bag) for child in keys(children)])
end

is_child (generic function with 1 method)

In [36]:
function num_of_parent_bags(tree, bag)
   return sum([is_child(tree, k, bag) for k in keys(tree)]) 
end

num_of_parent_bags (generic function with 1 method)

In [37]:
num_of_parent_bags(generate_tree(read_array(7, sep = r"\n")),"shiny gold bag")
    

142

In [38]:
function num_of_bags_inside(t, bag)
    children = t[bag]
    
    if length(children) == 0
        return 0
    end
    
    n = sum([num_of_bags_inside(t, b) * children[b] + children[b] for b in keys(children)])

    return n
end

num_of_bags_inside (generic function with 1 method)

In [39]:
num_of_bags_inside(generate_tree(read_array(7, sep = r"\n")), "shiny gold bag")

10219

## Day 8

In [40]:
function parse_code_find_loop(code)
   res = 0
   visited = []
    i = 1 #start with line 1
    while(true)
       if code[i, 1] ==  "acc"
            next_i = i+1
            next_res = res + parse(Int, code[i, 2])
        elseif code[i, 1] == "jmp"
            next_i = i + parse(Int, code[i, 2])
            next_res = res
        elseif code[i, 1] == "nop"
            next_i = i+1
            next_res = res
        end
        
        if next_i in visited
            display("current line $i")
            display(code[i,:])
            display("next line $next_i already visited")
            display(code[next_i,:])
            return res
        end
        
        append!(visited, i)
        
        i = next_i
        res = next_res
            
    end
end

parse_code_find_loop (generic function with 1 method)

In [41]:
parse_code_find_loop(read_array(8, ncol=2))

"current line 368"

2-element Array{SubString{String},1}:
 "jmp"
 "+153"

"next line 521 already visited"

2-element Array{SubString{String},1}:
 "jmp"
 "-272"

1867

In [42]:
function parse_code_fix_loop(code)
   res = 0
   visited = []
    i = 1 #start with line 1
    while(i <= size(code)[1])
       if code[i, 1] ==  "acc"
            next_i = i+1
            next_res = res + parse(Int, code[i, 2])
        elseif code[i, 1] == "jmp"
            next_i = i + parse(Int, code[i, 2])
            next_res = res
        elseif code[i, 1] == "nop"
            next_i = i+1
            next_res = res
        end
        
        if next_i in visited
            return false
        end
          
        append!(visited, i)
        
        i = next_i
        res = next_res
            
    end
    return res
end

parse_code_fix_loop (generic function with 1 method)

In [43]:
function try_change_code(code)
    for i in 1:size(code)[1]
        new_code = copy(code)
        
        # change code
       if  code[i, 1] ==  "acc"
            continue
        elseif code[i, 1] == "jmp"
            new_code[i, 1] = "nop"
        elseif code[i, 1] == "nop"
            new_code[i, 1] = "jmp"
        end
        
        # test new code
        res = parse_code_fix_loop(new_code)
        if res != false
            display("changed line $i")
            display(code[i, :])
            return res
        end
            
    end

end

try_change_code (generic function with 1 method)

In [44]:
try_change_code(read_array(8, ncol=2))

"changed line 278"

2-element Array{SubString{String},1}:
 "jmp"
 "+268"

1303

## Day 9 

In [45]:
function is_sum_of_two(a, sum)
    for i in 1:length(a)
        for j in i+1:length(a)
            if a[i] + a[j] == sum
                return true
            end
        end
    end
    return false
end

is_sum_of_two (generic function with 1 method)

In [46]:
function validate_XMAS_data(data; pre=25)
        data = parse.(Int, data)
    
        for i in pre+1:length(data)
            if !is_sum_of_two(data[i-pre:i-1], data[i])
                return data[i]
            end
        end
end


validate_XMAS_data (generic function with 1 method)

In [47]:
validate_XMAS_data(read_array(9))

25918798

In [48]:
function find_sum(data, sum)
    data = parse.(Int, data)
    for i in 1:length(data)-1
        total = 0
        j = i
        while  total <= sum
            total = total + data[j]
            if total == sum
                return(data[i:j])
            end
            j = j+1
        end
    end
end

find_sum (generic function with 1 method)

In [49]:
function calc_weakness(data)
   s =  validate_XMAS_data(read_array(9))
   l = find_sum(data, s)
   l = sort(l)
   display(sum(l))
    return l[1], l[length(l)]
end

calc_weakness (generic function with 1 method)

In [50]:
sum(calc_weakness(read_array(9)))

25918798

3340942

## Day 10

In [51]:
function sort_jolts(l)
    l = parse.(Int, l)
    # add 0
    l = vcat(0, l...)
    l = sort(l)
    # add 3 for device
    l = vcat(l, l[length(l)]+3)
    
    # get difference to the one before 
    # or use diff()
    l = [l[i]-l[i-1] for i in 2:length(l)]
    
    # count
    u=unique(l)
    d=Dict([(i,count(x->x==i,l)) for i in u])
    return d
end

sort_jolts (generic function with 1 method)

In [52]:
sort_jolts(read_array(10))

Dict{Int64,Int64} with 2 entries:
  3 => 32
  1 => 66

In [53]:
32*66

2112

In [54]:
function count_arrangements(l)
    l = parse.(Int, l)
    # add 0
    l = vcat(0, l...)
    l = sort(l)
    # add 3 for device
    l = vcat(l, l[length(l)]+3)
   
    #l = l[1:5]
    display("START")
    dct = Dict{Int,Int}()
    len = length(l)
    function helper(v, i)
        haskey(dct, i) && return dct[i] # schon gespeichert, this does the trick to reduce calc times!!!
        i == len && return 1 #ende erreicht
        
        n1 =               v[i+1] - v[i] <= 3 ? helper(v, i+1) : 0
        n2 = i+2 <= len && v[i+2] - v[i] <= 3 ? helper(v, i+2) : 0
        n3 = i+3 <= len && v[i+3] - v[i] <= 3 ? helper(v, i+3) : 0
        val = n1 + n2 + n3
        dct[i] = val
        return val
    end
    
    return helper(l, 1)
    
end

count_arrangements (generic function with 1 method)

In [55]:
count_arrangements(read_array(10))

"START"

3022415986688